import Razorpay from "razorpay";
import { ZodError } from "zod";
import { createPaymentOrderSchema } from "@/lib/schemas";
import { evaluatePolicy } from "@/lib/policy-engine";
import { getIdempotent, setIdempotent } from "@/lib/idempotency";
import { orderStore, appendAudit } from "@/lib/demo-store";
import { paise } from "@/lib/money";
import { ok, apiError, zodError } from "@/lib/api";
import type { DemoOrder } from "@/lib/types";
import { authorizeAgentRequest } from "@/lib/agent-auth";

export async function POST(request:Request){try{const body=createPaymentOrderSchema.parse(await request.json());if(!authorizeAgentRequest(request,body.agentId))return apiError("Agent authentication required",401);const key=request.headers.get("Idempotency-Key");if(!key||key.length<8)return apiError("A valid Idempotency-Key header is required",400);const cached=getIdempotent<Record<string,unknown>>(`payment-order:${key}`);if(cached)return ok({...cached,idempotentReplay:true});const decision=evaluatePolicy({action:"CREATE_ORDER",orderAmount:body.amount,agentBudget:body.budget});if(!decision.allowed)return ok({status:"BLOCKED",paymentInitiated:false,decision});if(decision.requiresApproval)return ok({status:"PENDING_APPROVAL",paymentInitiated:false,decision});const keyId=process.env.RAZORPAY_KEY_ID;const secret=process.env.RAZORPAY_KEY_SECRET;const configured=Boolean(keyId&&secret&&keyId.startsWith("rzp_test_"));if(keyId&&keyId.startsWith("rzp_live_"))return apiError("Live keys are not permitted. Use Razorpay Test Mode keys only.",403);const internalOrderId=`ord_${crypto.randomUUID().slice(0,8)}`;let razorpayOrderId:string;let provider:"razorpay"|"demo"="demo";if(configured){const razorpay=new Razorpay({key_id:keyId!,key_secret:secret!});const providerOrder=await razorpay.orders.create({amount:paise(body.amount),currency:"INR",receipt:internalOrderId,notes:{internalOrderId,agentId:body.agentId,sessionId:body.sessionId,environment:"test"}});razorpayOrderId=providerOrder.id;provider="razorpay"}else{razorpayOrderId=`order_test_demo_${crypto.randomUUID().slice(0,8)}`}
const order:DemoOrder={id:internalOrderId,razorpayOrderId,amount:body.amount,status:"PAYMENT_PENDING",itemIds:body.itemIds,agentId:body.agentId,createdAt:new Date().toISOString()};orderStore.set(internalOrderId,order);appendAudit({actor:"payment-service",actorType:"PAYMENT_SERVICE",action:"razorpay.order.create",summary:"Created Razorpay Test Order",status:"SUCCESS",amount:body.amount,metadata:{internalOrderId,razorpayOrderId,idempotencyKey:key,provider,mode:"test"}});const result={status:"PAYMENT_PENDING",internalOrderId,razorpayOrderId,amount:paise(body.amount),currency:"INR",keyId:configured?keyId:"rzp_test_demo",provider,mode:"test",decision};setIdempotent(`payment-order:${key}`,result);return ok(result,201)}catch(e){if(e instanceof ZodError)return zodError(e);return apiError("Test order creation failed safely",502,{paymentInitiated:false})}}
