"use client";
import { useState } from "react";
import { Check, Clock3, Megaphone, Play, ShieldCheck, Sparkles, Users } from "lucide-react";
import { campaigns } from "@/lib/demo-data";
import { Badge } from "@/components/ui/badge";
import { formatINR } from "@/lib/money";

export function CampaignBoard(){const [approved,setApproved]=useState<string[]>(["cmp_01"]);return <div className="grid gap-4 lg:grid-cols-3">{campaigns.map(c=>{const active=approved.includes(c.id);return <div className="card flex flex-col p-5" key={c.id}><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-soft text-brand"><Megaphone size={18}/></span><Badge tone={active?"green":c.status==="APPROVAL"?"amber":"purple"}>{active?"Active":c.status==="APPROVAL"?"Needs approval":"AI proposal"}</Badge></div><h3 className="mt-5 font-bold">{c.name}</h3><p className="mt-1 text-xs text-muted">{c.audience}</p><div className="mt-5 space-y-3 rounded-xl bg-[#F8F9FB] p-4 text-xs"><Row icon={Users} label="Audience" value={c.audience}/><Row icon={Sparkles} label="Offer" value={c.offer}/><Row icon={Clock3} label="Duration" value="48 hours"/></div><div className="mt-4 grid grid-cols-2 gap-2"><Metric label="Budget" value={formatINR(c.budget)}/><Metric label="Expected revenue" value={formatINR(c.revenue)} positive/></div><div className="mt-4 flex items-center gap-2 text-[10px] text-muted"><ShieldCheck size={13} className={c.budget<=5000?"text-mint":"text-amber"}/> Policy: {c.budget<=5000?"PASS · within budget":"Approval · budget > ₹5,000"}</div><button onClick={()=>setApproved(a=>[...a,c.id])} disabled={active} className={`mt-5 w-full ${active?"btn-secondary":"btn-primary"}`}>{active?<><Check size={15}/> Campaign active</>:<><Play size={15}/> Approve campaign</>}</button></div>})}</div>}
function Row({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string}){return <div className="flex items-start gap-2"><Icon size={13} className="mt-0.5 shrink-0 text-muted"/><span className="text-muted">{label}</span><strong className="ml-auto max-w-[55%] text-right font-semibold text-ink">{value}</strong></div>}
function Metric({label,value,positive}:{label:string;value:string;positive?:boolean}){return <div className="rounded-xl border border-line p-3"><p className="text-[9px] text-muted">{label}</p><p className={`mt-1 text-sm font-bold ${positive?"text-mint":""}`}>{value}</p></div>}
