"use client";
import { useState } from "react";
import { Check, ChevronDown, Play, ShieldCheck, Sparkles } from "lucide-react";
import { motion } from "framer-motion";
import { Badge } from "@/components/ui/badge";

export function OpportunityAction(){const [approved,setApproved]=useState(false);const [open,setOpen]=useState(false);return <div className="card overflow-hidden"><div className="border-b border-line p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand text-white"><Sparkles size={18}/></span><div><p className="eyebrow text-brand">Recommended action</p><h3 className="mt-1 font-bold">Create Keyboard + Mouse Bundle</h3></div></div><Badge tone={approved?"green":"amber"}>{approved?"Active":"Requires approval"}</Badge></div></div><div className="grid gap-px bg-line md:grid-cols-4"><Metric label="Current" value="₹2,898"/><Metric label="Bundle" value="₹2,699"/><Metric label="Expected lift" value="+8–12%" positive/><Metric label="Max exposure" value="₹199 / order"/></div><div className="p-5 sm:p-6"><div className="grid gap-3 sm:grid-cols-2"><Explain label="WHY" text="Views are up 31%, but keyboard conversion fell 14%. Mouse co-purchase intent is strong."/><Explain label="WHAT" text="Publish a 48-hour keyboard + mouse bundle to eligible high-intent sessions."/><Explain label="MONEY" text="Maximum discount exposure is ₹199 per converted order."/><Explain label="RISK" text="Low — inventory and 18% post-discount margin remain healthy."/></div><button onClick={()=>setOpen(!open)} className="mt-4 flex items-center gap-2 text-xs font-bold text-brand"><ShieldCheck size={14}/> Policy decision <ChevronDown size={14} className={open?"rotate-180":""}/></button>{open&&<motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} className="mt-3 rounded-xl border border-[#F1D6A4] bg-amber-soft p-4"><p className="text-xs font-bold text-[#945600]">REQUIRES_APPROVAL · nova-money-v3</p><div className="mt-3 grid gap-2 text-[11px] text-muted sm:grid-cols-3"><span className="flex gap-2"><Check size={13} className="text-mint"/> Discount ≤ 15%</span><span className="flex gap-2"><Check size={13} className="text-mint"/> Margin ≥ 12%</span><span className="flex gap-2"><Check size={13} className="text-mint"/> Exposure ≤ ₹500</span></div></motion.div>}<button disabled={approved} onClick={()=>setApproved(true)} className="btn-primary mt-5 w-full">{approved?<><Check size={16}/> Bundle activated in demo</>:<><Play size={16}/> Approve & activate bundle</>}</button></div></div>}
function Metric({label,value,positive}:{label:string;value:string;positive?:boolean}){return <div className="bg-white p-4"><p className="text-[10px] text-muted">{label}</p><p className={`mt-1 text-lg font-bold ${positive?"text-mint":""}`}>{value}</p></div>}
function Explain({label,text}:{label:string;text:string}){return <div className="subtle-card p-4"><p className="text-[10px] font-bold tracking-wider text-brand">{label}</p><p className="mt-2 text-xs leading-5 text-muted">{text}</p></div>}
