"use client";
import { useState } from "react";
import { ArrowDown, Bot, Braces, Check, Cpu, Database, Play, ShieldCheck, Sparkles, Wrench } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { Badge } from "@/components/ui/badge";

const pipeline=[{label:"Structured intent",icon:Braces},{label:"Tool registry",icon:Wrench},{label:"Schema validation",icon:Check},{label:"Policy engine",icon:ShieldCheck},{label:"Approval gate",icon:Bot}];
export function RevenueAgentConsole(){const [running,setRunning]=useState(false);const [complete,setComplete]=useState(false);const run=()=>{setRunning(true);setComplete(false);setTimeout(()=>{setRunning(false);setComplete(true)},1300)};return <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-line p-5 sm:p-6"><div className="flex items-center gap-3"><span className="relative flex h-11 w-11 items-center justify-center rounded-xl bg-[#17152D] text-[#AFA7FF]"><Cpu size={20}/><i className="absolute -right-1 -top-1 h-3 w-3 rounded-full border-2 border-white bg-mint"/></span><div><h2 className="font-bold">merchant-revenue-agent</h2><p className="mt-1 text-[10px] text-muted">Continuous opportunity monitor · last cycle 43s ago</p></div></div><Badge tone="green">Online</Badge></div><div className="p-5 sm:p-6"><div className="overflow-hidden rounded-xl border border-line bg-[#151427]"><div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><span className="mono text-[10px] text-white/50">SAFE AGENT EXECUTION · RUN #1842</span><span className="flex items-center gap-2 text-[9px] text-[#6FE1B5]"><i className="h-1.5 w-1.5 rounded-full bg-[#6FE1B5]"/> NO MONEY TOOLS EXPOSED</span></div><div className="p-5"><div className="flex min-w-[660px] items-center overflow-x-auto">{pipeline.map(({label,icon:Icon},i)=><div key={label} className="flex flex-1 items-center"><motion.div animate={running?{borderColor:["rgba(255,255,255,.1)","#7F75F5","rgba(255,255,255,.1)"]}:{}} transition={{delay:i*.18,duration:.5}} className="w-full rounded-xl border border-white/10 bg-white/[.04] p-3 text-white"><Icon size={15} className="text-[#AFA7FF]"/><p className="mt-4 text-[10px] font-semibold">{label}</p></motion.div>{i<pipeline.length-1&&<span className="mx-1 text-white/20">→</span>}</div>)}</div><AnimatePresence>{complete&&<motion.div initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} className="mt-4 flex items-center gap-2 rounded-lg border border-[#326B5A] bg-[#18372F] px-3 py-2 text-[10px] text-[#7EE6BF]"><Check size={13}/> 18,491 signals analyzed · 4 bounded opportunities emitted · audit committed</motion.div>}</AnimatePresence></div></div><button onClick={run} disabled={running} className="btn-primary mt-5 w-full">{running?<><span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-white/30 border-t-white"/> Analyzing signals…</>:<><Play size={15}/> Run agent cycle now</>}</button></div></section>
<section className="space-y-5"><div className="card p-5"><p className="eyebrow">Agent identity</p><div className="mt-4 rounded-xl bg-[#F7F7FC] p-4 mono text-[11px] leading-6 text-[#4E5666]"><p><span className="text-brand">agent:</span> merchant-revenue-agent</p><p><span className="text-brand">merchant:</span> mer_nova_001</p><p><span className="text-brand">session:</span> sys_continuous_8</p><p><span className="text-brand">policy:</span> nova-money-v3</p></div><p className="eyebrow mb-2 mt-5">Permissions</p><div className="flex flex-wrap gap-2">{["catalog.read","offer.create","campaign.propose","order.create"].map(x=><span className="rounded-md bg-brand-soft px-2 py-1 text-[10px] font-semibold text-brand-dark" key={x}>{x}</span>)}</div></div><div className="card p-5"><div className="flex items-center gap-2"><Database size={16} className="text-brand"/><h3 className="text-sm font-bold">Data boundaries</h3></div><ul className="mt-4 space-y-3 text-xs text-muted">{["No arbitrary SQL generation","No secret or key access","No policy mutation tools","No paid-state mutation","Merchant scoped reads only"].map(x=><li className="flex gap-2" key={x}><Check size={13} className="mt-0.5 text-mint"/>{x}</li>)}</ul></div></section></div>}
