"use client";
import { useState } from "react";
import { ArrowRight, BrainCircuit, Check, Sparkles } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { formatINR } from "@/lib/money";

export function RevenueSimulator(){
 const [stage,setStage]=useState<"idle"|"analyzing"|"done">("idle");
 const run=()=>{setStage("analyzing");setTimeout(()=>setStage("done"),1100)};
 return <div className="relative overflow-hidden rounded-2xl bg-[#17152D] p-6 text-white shadow-card"><div className="absolute -right-20 -top-20 h-52 w-52 rounded-full bg-brand/30 blur-3xl"/><div className="relative"><div className="flex items-center justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/10 text-[#B8B2FF]"><BrainCircuit size={20}/></span><span className="rounded-full border border-white/10 bg-white/[.06] px-2.5 py-1 text-[9px] font-bold uppercase tracking-[.12em] text-white/60">Revenue simulator</span></div><h3 className="mt-6 text-xl font-bold tracking-[-.03em]">What should I do next?</h3><p className="mt-2 text-xs leading-5 text-white/55">Analyze live demo signals and rank the safest, highest-impact actions.</p>
 <AnimatePresence mode="wait">{stage==="idle"&&<motion.button key="idle" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={run} className="mt-6 flex w-full items-center justify-between rounded-xl bg-white px-4 py-3 text-sm font-bold text-ink">Run revenue analysis <Sparkles size={16} className="text-brand"/></motion.button>}{stage==="analyzing"&&<motion.div key="loading" initial={{opacity:0}} animate={{opacity:1}} className="mt-6 rounded-xl border border-white/10 bg-white/[.05] p-4"><div className="flex items-center gap-3 text-xs"><span className="h-4 w-4 animate-spin rounded-full border-2 border-white/20 border-t-[#AFA7FF]"/> Mapping 18,491 revenue signals…</div><div className="mt-4 h-1 overflow-hidden rounded-full bg-white/10"><motion.div className="h-full bg-[#8C82FF]" initial={{width:0}} animate={{width:"92%"}} transition={{duration:1}}/></div></motion.div>}{stage==="done"&&<motion.div key="done" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="mt-5"><div className="grid grid-cols-2 gap-2"><DarkStat label="Current" value="₹4.82L"/><DarkStat label="Projected" value="₹5.27L"/></div><div className="mt-2 flex items-center justify-between rounded-xl border border-[#5A517D] bg-[#292642] p-3"><span className="text-xs text-white/60">Potential uplift</span><span className="text-lg font-bold text-[#65D6AA]">+9.4%</span></div><div className="mt-3 flex items-start gap-2 text-[9px] leading-4 text-white/45"><Check size={12} className="mt-0.5 shrink-0 text-[#65D6AA]"/> AI projection based on demo data. Not guaranteed revenue.</div><button onClick={()=>setStage("idle")} className="mt-3 flex items-center gap-1 text-[10px] font-bold text-[#B8B2FF]">View all 4 opportunities <ArrowRight size={12}/></button></motion.div>}</AnimatePresence></div></div>
}
function DarkStat({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/10 bg-white/[.045] p-3"><p className="text-[9px] uppercase tracking-wider text-white/45">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>}
