import { ZodError } from "zod";
import { products } from "@/lib/demo-data";
import { offerSchema } from "@/lib/schemas";
import { evaluatePolicy } from "@/lib/policy-engine";
import { offerStore } from "@/lib/agent-store";
import { appendAudit } from "@/lib/demo-store";
import { ok, apiError, zodError } from "@/lib/api";
import { findServerApproval } from "@/lib/approval-store";
import { authorizeAgentRequest } from "@/lib/agent-auth";
export async function POST(request:Request){try{const body=offerSchema.parse(await request.json());if(!authorizeAgentRequest(request,body.agentId))return apiError("Agent authentication required",401);const selected=body.productIds.map(id=>products.find(p=>p.id===id)).filter((p):p is NonNullable<typeof p>=>Boolean(p));if(selected.length!==body.productIds.length)return apiError("One or more products do not exist",404);if(selected.some(p=>p.stock<1))return apiError("Inventory unavailable",409);const listPrice=selected.reduce((s,p)=>s+p.price,0);const cost=selected.reduce((s,p)=>s+p.cost,0);const recommendedPrice=listPrice===4996?4499:Math.round(listPrice*.93);const requested=body.requestedPrice??recommendedPrice;const floor=listPrice===4996?4299:Math.ceil(listPrice*.85);const offerPrice=Math.max(requested,floor);const decision=evaluatePolicy({action:"CREATE_OFFER",listPrice,offerPrice,negotiationBasePrice:recommendedPrice,cost,minimumMarginPercent:12});if(!decision.allowed){appendAudit({actor:"policy-engine",actorType:"POLICY_ENGINE",action:"offer.block",summary:decision.reason,status:"WARNING",amount:offerPrice,metadata:{agentId:body.agentId,policy:decision.policyVersion}});return ok({schema:"rpay.agent.offer.v1",status:"BLOCKED",offerPrice:null,counterOffer:floor,decision},200)}const id=`off_${crypto.randomUUID().slice(0,8)}`;const serverApproval=decision.requiresApproval?findServerApproval({agentId:body.agentId,productIds:body.productIds,offerPrice}):undefined;const approvalId=serverApproval?.id;const finalStatus=decision.requiresApproval?(serverApproval?"APPROVED_BY_MERCHANT":"PENDING_APPROVAL"):"AUTO_APPROVED";offerStore.set(id,{id,agentId:body.agentId,productIds:body.productIds,listPrice,offerPrice,status:finalStatus,approvalId});appendAudit({actor:"merchant-revenue-agent",actorType:"REVENUE_AGENT",action:"offer.create",summary:`Created bounded offer for ₹${offerPrice}`,status:"SUCCESS",amount:offerPrice,metadata:{offerId:id,agentId:body.agentId,decision:decision.status,approvalId:approvalId??"none"}});return ok({schema:"rpay.agent.offer.v1",offerId:id,listPrice,offerPrice,currency:"INR",savings:listPrice-offerPrice,products:selected.map(p=>({id:p.id,name:p.name,quantity:1})),status:finalStatus,approvalId,approvedBy:serverApproval?.approvedBy,decision,expiresAt:new Date(Date.now()+15*60_000).toISOString()})}catch(error){if(error instanceof ZodError)return zodError(error);return apiError("Offer request failed safely",500)}}
