"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { AlertTriangle, ArrowLeft, ArrowRight, Bot, Check, CheckCircle2, ChevronDown, CircleDollarSign, Clock3, CreditCard, Fingerprint, LockKeyhole, MessageSquare, PackageCheck, RefreshCw, Send, ShieldCheck, ShoppingBag, ShoppingCart, Sparkles, Store, TerminalSquare, UserRound, WalletCards, XCircle, Zap } from "lucide-react";
import { Logo } from "@/components/ui/logo";
import { TestMode } from "@/components/ui/test-mode";
import { Badge } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";
import { products } from "@/lib/demo-data";
import { formatINR } from "@/lib/money";

type Phase="idle"|"discovering"|"discovered"|"negotiating"|"offered"|"checkout"|"paid"|"failed";
type PaymentConfig={provider:"razorpay"|"demo";keyId:string;razorpayOrderId:string;internalOrderId:string;amount:number};
type Message={id:string;side:"buyer"|"merchant"|"user";label:string;text:string;meta?:string};
const bundleIds=["prod_keyboard","prod_mouse","prod_stand","prod_lamp"];
const bundle=products.filter(p=>bundleIds.includes(p.id));
const traceBase=[{label:"User intent",detail:"WFH setup · budget ₹5,000",status:"done"},{label:"Merchant discovery",detail:"/.well-known/agent-commerce",status:"done"}];

export function BuyerApp(){
 const [phase,setPhase]=useState<Phase>("idle");
 const [input,setInput]=useState("");
 const [traceOpen,setTraceOpen]=useState(true);
 const [whyOpen,setWhyOpen]=useState(false);
 const [paymentOpen,setPaymentOpen]=useState(false);
 const [internalOrder,setInternalOrder]=useState("");
 const [paymentConfig,setPaymentConfig]=useState<PaymentConfig|null>(null);
 const [messages,setMessages]=useState<Message[]>([{id:"hello",side:"buyer",label:"AI Buyer",text:"I’m connected to Nova Electronics through its Agent Commerce API. Tell me the outcome you want—not a product name.",meta:"buyer-agent-7821 · ₹5,000 authority"}]);
 const paid=phase==="paid";
 const failed=phase==="failed";
 const spent=paid?4299:0;
 const traces=useMemo(()=>{
  const list=[...traceBase];
  if(["discovered","negotiating","offered","checkout","paid","failed"].includes(phase)) list.push({label:"Catalog search",detail:"4 intent-matched products",status:"done"});
  if(["offered","checkout","paid","failed"].includes(phase)) list.push({label:"Offer + negotiation",detail:"₹4,499 → ₹4,299",status:"done"},{label:"Policy + approval",detail:"4 checks · merchant approved",status:"done"});
  if(["checkout","paid","failed"].includes(phase)) list.push({label:"Checkout",detail:"Budget + amount locked",status:"done"});
  if(paid) list.push({label:"Payment verification",detail:"Server HMAC verified",status:"done"},{label:"Order confirmed",detail:internalOrder||"ord_demo",status:"done"});
  if(failed) list.push({label:"Payment failure",detail:"UNPAID · cart preserved",status:"failed"});
  return list;
 },[phase,paid,failed,internalOrder]);

 const add=(...m:Message[])=>setMessages(old=>[...old,...m]);
 const discover=async()=>{if(phase==="discovering")return;setPhase("discovering");add({id:crypto.randomUUID(),side:"user",label:"Customer",text:"I need a work-from-home setup under ₹5,000."});try{await fetch("/api/agent/search?q=work%20from%20home&budget=5000&limit=4",{headers:{"x-agent-id":"buyer-agent-7821","x-agent-session":"sess_83921"}});}catch{}setTimeout(()=>{setPhase("discovered");add({id:crypto.randomUUID(),side:"buyer",label:"AI Buyer",text:"I found a complete setup: mechanical keyboard, wireless mouse, laptop stand and desk lamp. List total is ₹4,996.",meta:"4 catalog matches · inventory confirmed"},{id:crypto.randomUUID(),side:"merchant",label:"Merchant Revenue Agent",text:"I can package those as the Work From Home Bundle for ₹4,499. The 9.9% offer is auto-approved under nova-money-v3.",meta:"Offer off_wfh_4499 · LOW risk"});},750)};
 const negotiate=async()=>{setPhase("negotiating");add({id:crypto.randomUUID(),side:"buyer",label:"AI Buyer",text:"My customer’s target is ₹4,200. Can you improve the offer?",meta:"Requested on behalf of customer"});let counter=4299;try{const r=await fetch("/api/agent/offer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({agentId:"buyer-agent-7821",sessionId:"sess_83921",productIds:bundleIds,requestedPrice:4200,budget:5000})});const json=await r.json();counter=json?.data?.offerPrice??counter;}catch{}setTimeout(()=>{setPhase("offered");add({id:crypto.randomUUID(),side:"merchant",label:"Merchant Revenue Agent",text:`₹4,200 would cross my configured floor. I can offer ₹${counter.toLocaleString("en-IN")} with all four items. Total discount 13.95%; merchant approval is attached.`,meta:"Policy PASS · apr_204 · expires in 15 min"},{id:crypto.randomUUID(),side:"buyer",label:"AI Buyer",text:"This stays within the ₹5,000 authority. I recommend accepting—the bundle is ₹697 below list and matches the full intent.",meta:"Budget remaining after purchase: ₹701"});},700)};
 const checkout=async()=>{setPhase("checkout");setPaymentOpen(true);try{const r=await fetch("/api/payments/create-order",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":"idem_sess_83921_checkout"},body:JSON.stringify({agentId:"buyer-agent-7821",sessionId:"sess_83921",amount:4299,budget:5000,itemIds:bundleIds})});const j=await r.json();const data=j?.data;const id=data?.internalOrderId||"ord_demo_842";setInternalOrder(id);setPaymentConfig(data?{provider:data.provider,keyId:data.keyId,razorpayOrderId:data.razorpayOrderId,internalOrderId:id,amount:data.amount}:null);}catch{setInternalOrder("ord_demo_842");setPaymentConfig({provider:"demo",keyId:"rzp_test_demo",razorpayOrderId:"order_test_demo_seed",internalOrderId:"ord_demo_842",amount:429900})}};
 const markPaid=()=>{setPaymentOpen(false);setPhase("paid");add({id:crypto.randomUUID(),side:"buyer",label:"AI Buyer",text:"Payment verified and order confirmed. I spent ₹4,299 of the authorized ₹5,000 budget.",meta:"Razorpay Test Mode · signature verified server-side"});};
 const completePayment=async()=>{try{await fetch("/api/payments/demo-complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({internalOrderId:internalOrder||"ord_demo_842"})});}catch{}markPaid();};
 const failPayment=async()=>{try{await fetch("/api/payments/fail",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({internalOrderId:internalOrder||"ord_demo_842",reason:"TEST_PAYMENT_FAILED"})});}catch{}setPaymentOpen(false);setPhase("failed");add({id:crypto.randomUUID(),side:"buyer",label:"AI Buyer",text:"Payment failed safely. ₹0 charged, no paid order was created, and the cart has been preserved for retry.",meta:"Verified provider state: FAILED · audit event recorded"});};
 const send=()=>{if(!input.trim())return;const text=input;setInput("");add({id:crypto.randomUUID(),side:"user",label:"Customer",text});if(phase==="idle")discover();else if(phase==="discovered")negotiate()};
 return <div className="min-h-screen bg-[#F5F6FA]">
  <header className="sticky top-0 z-30 flex h-[68px] items-center justify-between border-b border-line bg-white/90 px-4 backdrop-blur-xl sm:px-6"><div className="flex items-center gap-4"><Logo/><span className="hidden h-5 w-px bg-line sm:block"/><span className="hidden text-xs font-semibold text-muted sm:block">AI Buyer Workspace</span></div><div className="flex items-center gap-2"><TestMode compact/><Link href="/api/auth/demo?next=/dashboard/overview" className="btn-secondary !px-3 !py-2"><ArrowLeft size={14}/><span className="hidden sm:inline">Merchant console</span></Link></div></header>
  <main className="mx-auto grid max-w-[1520px] gap-4 p-3 sm:p-5 xl:grid-cols-[270px_minmax(0,1fr)_320px]">
   <aside className="order-2 space-y-4 xl:order-1"><AgentIdentity/><BudgetCard spent={spent}/><div className="card p-4"><p className="eyebrow">Discovered merchant</p><div className="mt-4 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#17152D] text-white"><Store size={18}/></span><div><p className="text-sm font-bold">Nova Electronics</p><p className="mt-0.5 text-[10px] text-muted">7 products · INR · test</p></div></div><div className="mt-4 flex flex-wrap gap-1.5">{["catalog","offers","checkout","payment"].map(x=><span key={x} className="rounded-md bg-[#F1F2F6] px-2 py-1 text-[9px] font-semibold text-muted">{x}</span>)}</div></div></aside>
   <section className="order-1 flex min-h-[calc(100vh-108px)] flex-col overflow-hidden rounded-2xl border border-line bg-white shadow-card xl:order-2"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-line px-4 py-4 sm:px-6"><div className="flex items-center gap-3"><span className="relative flex h-10 w-10 items-center justify-center rounded-xl bg-brand text-white"><Bot size={19}/><i className="absolute -right-1 -top-1 h-3 w-3 rounded-full border-2 border-white bg-mint"/></span><div><h1 className="text-sm font-bold">RPay AI Buyer</h1><p className="mt-0.5 text-[10px] text-muted">Shopping as buyer-agent-7821 · bounded autonomy</p></div></div><button onClick={()=>setTraceOpen(!traceOpen)} className={`btn-secondary !py-2 ${traceOpen?"!border-[#CCC7FF] !bg-brand-soft !text-brand":""}`}><TerminalSquare size={14}/> Agent Trace</button></div>
    <div className="flex-1 space-y-5 overflow-y-auto p-4 sm:p-6">{messages.map(m=><MessageBubble key={m.id} message={m}/>) }
      {phase==="discovering"&&<Typing label="Searching Nova’s Agent Commerce API…"/>}
      {["discovered","negotiating","offered","checkout","paid","failed"].includes(phase)&&<ProductStrip/>}
      {phase==="negotiating"&&<Typing label="Merchant agent is evaluating pricing policy…"/>}
      {phase==="offered"&&<DealCard onWhy={()=>setWhyOpen(true)} onAccept={checkout}/>} 
      {failed&&<FailureCard onRetry={()=>{setPhase("offered");setPaymentOpen(false)}}/>}
      {paid&&<SuccessCard order={internalOrder||"ord_demo_842"}/>} 
    </div>
    <div className="border-t border-line bg-[#FCFCFD] p-3 sm:p-4">{phase==="idle"&&<button onClick={discover} className="mb-3 flex w-full items-center justify-between rounded-xl border border-[#DAD6FF] bg-brand-soft px-4 py-3 text-left text-xs font-semibold text-brand-dark"><span className="flex items-center gap-2"><Sparkles size={15}/> I need a work-from-home setup under ₹5,000</span><ArrowRight size={15}/></button>}{phase==="discovered"&&<button onClick={negotiate} className="mb-3 flex w-full items-center justify-between rounded-xl border border-[#F1D6A4] bg-amber-soft px-4 py-3 text-left text-xs font-semibold text-[#875000]"><span className="flex items-center gap-2"><MessageSquare size={15}/> Ask: “Can you make it ₹4,200?”</span><ArrowRight size={15}/></button>}<div className="flex items-end gap-2 rounded-xl border border-line bg-white p-2 shadow-sm focus-within:border-brand/40"><textarea rows={1} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Describe what you need or negotiate an offer…" className="max-h-28 min-h-10 flex-1 resize-none bg-transparent px-2 py-2 text-xs outline-none placeholder:text-[#9AA1AE]"/><button onClick={send} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-brand text-white"><Send size={15}/></button></div><p className="mt-2 text-center text-[9px] text-muted">AI Buyer can only transact within identity, budget and merchant policy.</p></div>
   </section>
   <aside className={`order-3 ${traceOpen?"block":"hidden xl:block"}`}><AgentTrace traces={traces}/></aside>
  </main>
  <Modal open={whyOpen} onClose={()=>setWhyOpen(false)} title="Why was ₹4,299 allowed?"><div className="rounded-xl border border-[#DAD6FF] bg-brand-soft p-4"><p className="text-xs font-bold text-brand-dark">Decision summary · user-facing factors</p><p className="mt-2 text-xs leading-5 text-muted">This shows business signals and policy checks, not private chain-of-thought.</p></div><div className="mt-5 space-y-3">{[["Discount","13.95% ≤ 15%",true],["Negotiation exposure","₹697 total vs list; merchant approved",true],["Bundle margin","17.3% ≥ 12%",true],["Agent budget","₹4,299 ≤ ₹5,000",true],["Inventory","All 4 products available",true]].map(([a,b])=><div key={String(a)} className="flex items-center gap-3 rounded-xl border border-line p-3"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-mint-soft text-mint"><Check size={13}/></span><div><p className="text-xs font-semibold">{a}</p><p className="mt-0.5 text-[10px] text-muted">{b}</p></div></div>)}</div><div className="mt-5 grid grid-cols-3 gap-2"><Mini label="Confidence" value="87%"/><Mini label="Risk" value="LOW"/><Mini label="Approval" value="apr_204"/></div></Modal>
  <PaymentModal open={paymentOpen} onClose={()=>setPaymentOpen(false)} onDemoSuccess={completePayment} onVerified={markPaid} onFailure={failPayment} order={internalOrder} config={paymentConfig}/>
 </div>
}

function AgentIdentity(){return <div className="card p-4"><div className="flex items-center justify-between"><p className="eyebrow">Agent identity</p><Badge tone="green">Authorized</Badge></div><div className="mt-4 rounded-xl bg-[#F7F7FC] p-3 mono text-[10px] leading-5 text-[#51596A]"><p><span className="text-brand">agent</span>: buyer-agent-7821</p><p><span className="text-brand">role</span>: AI Buyer</p><p><span className="text-brand">purpose</span>: electronics</p><p><span className="text-brand">session</span>: sess_83921</p></div></div>}
function BudgetCard({spent}:{spent:number}){const remaining=5000-spent;return <div className="overflow-hidden rounded-2xl bg-[#17152D] p-4 text-white shadow-card"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider text-white/60"><WalletCards size={14}/> Transaction budget</div><LockKeyhole size={13} className="text-[#AFA7FF]"/></div><p className="mt-5 text-[10px] text-white/45">Authorized maximum</p><p className="mt-1 text-2xl font-bold tracking-[-.04em]">₹5,000</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/10"><motion.div className="h-full bg-[#8D83FF]" animate={{width:`${spent/50}%`}}/></div><div className="mt-3 grid grid-cols-2 gap-2 text-[10px]"><div><p className="text-white/40">Spent</p><p className="mt-1 font-bold">{formatINR(spent)}</p></div><div><p className="text-white/40">Remaining</p><p className="mt-1 font-bold text-[#76DEB6]">{formatINR(remaining)}</p></div></div></div>}
function MessageBubble({message:m}:{message:Message}){const user=m.side==="user";const merchant=m.side==="merchant";return <div className={`flex gap-3 ${user?"justify-end":""}`}>{!user&&<span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${merchant?"bg-[#17152D] text-[#AFA7FF]":"bg-brand-soft text-brand"}`}>{merchant?<Zap size={14}/>:<Bot size={15}/>}</span>}<div className={`max-w-[84%] ${user?"rounded-2xl rounded-br-md bg-brand px-4 py-3 text-white":""}`}>{!user&&<p className="mb-1.5 text-[9px] font-bold uppercase tracking-wider text-muted">{m.label}</p>}<p className={`text-xs leading-5 ${user?"text-white":"text-ink"}`}>{m.text}</p>{m.meta&&<p className={`mt-2 text-[9px] ${user?"text-white/60":"text-muted"}`}>{m.meta}</p>}</div>{user&&<span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[#E9EAF0] text-muted"><UserRound size={14}/></span>}</div>}
function Typing({label}:{label:string}){return <div className="flex items-center gap-3 text-[10px] text-muted"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-soft text-brand"><Bot size={14}/></span><span className="flex items-center gap-2 rounded-xl bg-[#F6F7F9] px-3 py-2"><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-brand"/><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-brand [animation-delay:120ms]"/><i className="h-1.5 w-1.5 animate-bounce rounded-full bg-brand [animation-delay:240ms]"/>{label}</span></div>}
function ProductStrip(){return <div><p className="eyebrow mb-3">Intent-matched bundle</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{bundle.map(p=><div className="rounded-xl border border-line p-3" key={p.id}><span style={{background:p.accent}} className="flex h-9 w-9 items-center justify-center rounded-lg text-base">{p.icon}</span><p className="mt-3 truncate text-[10px] font-bold">{p.name}</p><p className="mt-1 text-[10px] text-muted">{formatINR(p.price)}</p></div>)}</div></div>}
function DealCard({onWhy,onAccept}:{onWhy:()=>void;onAccept:()=>void}){return <motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="overflow-hidden rounded-2xl border border-[#CFCBFF] bg-[#FAF9FF]"><div className="flex flex-wrap items-start justify-between gap-3 p-5"><div><div className="flex items-center gap-2"><Sparkles size={15} className="text-brand"/><p className="eyebrow text-brand">Negotiated offer</p></div><h3 className="mt-3 text-lg font-bold">Work From Home Bundle</h3><p className="mt-1 text-xs text-muted"><span className="line-through">₹4,996</span><span className="ml-2">You save ₹697</span></p></div><div className="text-right"><p className="text-2xl font-bold tracking-[-.04em]">₹4,299</p><Badge tone="green" className="mt-2"><ShieldCheck size={11}/> Policy pass</Badge></div></div><div className="grid grid-cols-3 border-y border-[#E4E1FF] bg-white/70 text-center"><Mini label="Discount" value="13.95%"/><Mini label="Risk" value="LOW"/><Mini label="Expires" value="15 min"/></div><div className="flex flex-col gap-2 p-4 sm:flex-row"><button onClick={onWhy} className="btn-secondary flex-1">Show me why</button><button onClick={onAccept} className="btn-primary flex-1"><CreditCard size={15}/> Accept & checkout</button></div></motion.div>}
function Mini({label,value}:{label:string;value:string}){return <div className="border-r border-line p-3 last:border-0"><p className="text-[9px] text-muted">{label}</p><p className="mt-1 text-xs font-bold">{value}</p></div>}
function AgentTrace({traces}:{traces:Array<{label:string;detail:string;status:string}>}){return <div className="card sticky top-[88px] overflow-hidden"><div className="flex items-center justify-between border-b border-line p-4"><div className="flex items-center gap-2"><TerminalSquare size={16} className="text-brand"/><h2 className="text-sm font-bold">Agent Trace</h2></div><span className="h-2 w-2 animate-pulse rounded-full bg-mint"/></div><div className="p-4">{traces.map((t,i)=><div className="relative flex gap-3 pb-5 last:pb-0" key={`${t.label}-${i}`}>{i<traces.length-1&&<span className="absolute left-[9px] top-5 h-full w-px bg-line"/>}<span className={`z-10 mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full ${t.status==="failed"?"bg-rose-soft text-rose":"bg-mint-soft text-mint"}`}>{t.status==="failed"?<XCircle size={12}/>:<Check size={11}/>}</span><div><p className="text-[10px] font-bold uppercase tracking-wider">{t.label}</p><p className="mt-1 text-[9px] leading-4 text-muted">{t.detail}</p></div></div>)}</div><div className="border-t border-line bg-[#FAFBFC] p-4"><p className="text-[9px] leading-4 text-muted"><Fingerprint size={11} className="mr-1 inline text-brand"/> Structured decisions only. No hidden reasoning or secrets exposed.</p></div></div>}
function PaymentModal({open,onClose,onDemoSuccess,onVerified,onFailure,order,config}:{open:boolean;onClose:()=>void;onDemoSuccess:()=>void;onVerified:()=>void;onFailure:()=>void;order:string;config:PaymentConfig|null}){
 const [paying,setPaying]=useState(false);const [error,setError]=useState("");
 const startPayment=async()=>{if(!config)return;if(config.provider==="demo"){setPaying(true);await onDemoSuccess();return}setPaying(true);setError("");try{await loadRazorpay();const RazorpayCheckout=(window as unknown as {Razorpay:new(options:Record<string,unknown>)=>{open:()=>void}}).Razorpay;const checkout=new RazorpayCheckout({key:config.keyId,amount:config.amount,currency:"INR",name:"Nova Electronics",description:"Work From Home Bundle · Test Mode",order_id:config.razorpayOrderId,handler:async(response:{razorpay_order_id:string;razorpay_payment_id:string;razorpay_signature:string})=>{const verify=await fetch("/api/payments/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...response,internalOrderId:config.internalOrderId})});if(!verify.ok){setError("Server verification failed. Order remains unpaid.");setPaying(false);return}onVerified();},modal:{ondismiss:()=>setPaying(false)},theme:{color:"#5B4CFF"}});checkout.open()}catch{setError("Razorpay Checkout could not load. No payment was initiated.");setPaying(false)}};
 return <Modal open={open} onClose={onClose} title="Secure Test Checkout"><div className="mb-5 flex justify-center"><TestMode/></div><div className="rounded-xl bg-[#17152D] p-5 text-white"><div className="flex items-center justify-between"><div><p className="text-[10px] text-white/50">Amount locked</p><p className="mt-1 text-3xl font-bold">₹4,299</p></div><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/10"><CreditCard size={20}/></span></div><div className="mt-5 flex items-center justify-between border-t border-white/10 pt-4 mono text-[9px] text-white/45"><span>{order||"Creating Razorpay Test Order…"}</span><span>{config?.provider==="razorpay"?"RAZORPAY CHECKOUT":"DEMO FALLBACK"}</span></div></div><div className="mt-4 grid grid-cols-2 gap-2 text-[10px]"><div className="subtle-card p-3"><ShieldCheck size={14} className="text-mint"/><p className="mt-2 font-semibold">Server verified</p><p className="mt-1 text-muted">HMAC-SHA256</p></div><div className="subtle-card p-3"><LockKeyhole size={14} className="text-brand"/><p className="mt-2 font-semibold">Amount immutable</p><p className="mt-1 text-muted">429,900 paise</p></div></div>{error&&<p className="mt-3 rounded-lg bg-rose-soft p-3 text-[10px] font-semibold text-rose">{error}</p>}<button onClick={startPayment} disabled={!order||paying} className="btn-primary mt-4 w-full"><CheckCircle2 size={16}/> {paying?"Opening secure checkout…":config?.provider==="razorpay"?"Pay with Razorpay Test Checkout":"Complete verified demo payment"}</button><button onClick={onFailure} disabled={!order||paying} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl border border-[#FFD0D2] bg-rose-soft px-4 py-2.5 text-xs font-bold text-[#B72D32]"><AlertTriangle size={14}/> Simulate Payment Failure</button><p className="mt-3 text-center text-[9px] text-muted">{config?.provider==="razorpay"?"Razorpay Test Checkout is enabled. The server verifies before PAID.":"Demo fallback emulates a signed Test Mode response; no provider charge occurs."}</p></Modal>}
async function loadRazorpay(){if((window as unknown as {Razorpay?:unknown}).Razorpay)return;await new Promise<void>((resolve,reject)=>{const script=document.createElement("script");script.src="https://checkout.razorpay.com/v1/checkout.js";script.onload=()=>resolve();script.onerror=()=>reject(new Error("checkout load failed"));document.body.appendChild(script)})}
function FailureCard({onRetry}:{onRetry:()=>void}){return <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="rounded-2xl border border-[#FFD0D2] bg-rose-soft p-5"><div className="flex items-start gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-white text-rose"><XCircle size={18}/></span><div><h3 className="text-sm font-bold text-[#A8282D]">Payment failed safely</h3><p className="mt-1 text-xs leading-5 text-[#8E5558]">₹0 charged · order remains UNPAID · cart preserved · audit recorded.</p></div></div><button onClick={onRetry} className="btn-secondary mt-4 w-full !border-[#F1B9BB]"><RefreshCw size={14}/> Retry with preserved cart</button></motion.div>}
function SuccessCard({order}:{order:string}){return <motion.div initial={{opacity:0,scale:.98}} animate={{opacity:1,scale:1}} className="rounded-2xl border border-[#BDE7D4] bg-mint-soft p-5"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-white text-mint"><PackageCheck size={20}/></span><div><h3 className="text-sm font-bold text-[#086E4E]">Order confirmed</h3><p className="mt-1 text-xs leading-5 text-[#487463]">Payment signature verified server-side. Audit trace is complete.</p><p className="mono mt-2 text-[9px] text-[#487463]">{order} · PAID · ₹4,299</p></div></div></motion.div>}
